spring:
  profiles:
    active:
      - dev
---
server:
  port: 820123
spring:
  profile: dev
  application:
      name: spirng-cloud-config-client
content: hello dev11
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name:  spring-cloud-config-client
content: hello test22
