server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: eureka-provider-6001
spring:
  application:
    name: eureka-provider
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  port: ${server.port}
  appName: eureka-provider-6001
  companyName: www.wanho.net 1993
  other: other
