server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    #    显示ip
    prefer-ip-address: true
    #    Status显示名
    instance-id: eureka-provider-6001
    #需要增加下面配置，告诉注册中心访问路径变化
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
spring:
  application:
    #    Application名称
    name: eureka-provider
management:
  server:
  #actuator端口
  #    port: 9001
  endpoints:
    web:
      #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always
info:
  port: ${server.port}
  appName: eureka-provider-6001
  companyName: www.wanho.net456
  other: other

